package kg.edu.mathbilim.mapper.event;

import kg.edu.mathbilim.dto.event.EventTypeDto;
import kg.edu.mathbilim.dto.event.EventTypeTranslationDto;
import kg.edu.mathbilim.dto.post.PostTypeDto;
import kg.edu.mathbilim.dto.post.PostTypeTranslationDto;
import kg.edu.mathbilim.mapper.TypeBaseMapper;
import kg.edu.mathbilim.mapper.post.PostTypeTranslationMapper;
import kg.edu.mathbilim.mapper.post.PostTypeTranslationMapperImpl;
import kg.edu.mathbilim.model.event.EventType;
import kg.edu.mathbilim.model.event.EventTypeTranslation;
import kg.edu.mathbilim.model.post.PostType;
import kg.edu.mathbilim.model.post.PostTypeTranslation;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface EventTypeMapper  extends TypeBaseMapper<
        EventType,
        EventTypeDto,
        EventTypeTranslation,
        EventTypeTranslationDto,
        EventTypeTranslationMapper> {

        @Override
        EventTypeDto toDto(EventType entity);

        @Override
        EventType toEntity(EventTypeDto dto);

        @Override
        default EventTypeTranslationMapper getTranslationMapper() {
            return new EventTypeTranslationMapperImpl(); // Generated by MapStruct
        }
}
