ALTER TABLE olympiads
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE tests
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE organizations
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;
