ALTER TABLE blogs
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE news
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE events
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE books
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE posts
    ADD COLUMN deleted BOOLEAN DEFAULT FALSE NOT NULL;
