package kg.edu.mathbilim.mapper.reference;

import kg.edu.mathbilim.dto.reference.CategoryDto;
import kg.edu.mathbilim.dto.reference.CategoryTranslationDto;
import kg.edu.mathbilim.dto.user.UserTypeDto;
import kg.edu.mathbilim.dto.user.UserTypeTranslationDto;
import kg.edu.mathbilim.mapper.TypeBaseMapper;
import kg.edu.mathbilim.mapper.user.UserTypeTranslationMapper;
import kg.edu.mathbilim.mapper.user.UserTypeTranslationMapperImpl;
import kg.edu.mathbilim.model.reference.Category;
import kg.edu.mathbilim.model.reference.CategoryTranslation;
import kg.edu.mathbilim.model.user.UserType;
import kg.edu.mathbilim.model.user.UserTypeTranslation;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CategoryMapper extends TypeBaseMapper<
        Category,
        CategoryDto,
        CategoryTranslation,
        CategoryTranslationDto,
        CategoryTranslationMapper> {

        @Override
        CategoryDto toDto(Category entity);

        @Override
        Category toEntity(CategoryDto dto);
        @Override
        default CategoryTranslationMapper getTranslationMapper() {
            return new CategoryTranslationMapperImpl(); // Generated by MapStruct
        }
}
