-- changelog Aisha: 029 insert file types

INSERT INTO file_types (name, mime_type, extension)
VALUES ('PDF Document', 'application/pdf', 'pdf'),
       ('JPEG Image', 'image/jpeg', 'jpg'),
       ('PNG Image', 'image/png', 'png'),
       ('MP4 Video', 'video/mp4', 'mp4'),
       ('MP3 Audio', 'audio/mpeg', 'mp3'),
       ('ZIP Archive', 'application/zip', 'zip'),
       ('Microsoft Word', 'application/msword', 'doc'),
       ('Microsoft Excel', 'application/vnd.ms-excel', 'xls'),
       ('Text Document', 'text/plain', 'txt'),
       ('WebP Image', 'image/webp', 'webp'),
       ('GIF Image', 'image/gif', 'gif'),
       ('SVG Image', 'image/svg+xml', 'svg'),
       ('Microsoft Word DOCX', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx'),
       ('Microsoft Excel XLSX', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx'),
       ('Microsoft PowerPoint', 'application/vnd.ms-powerpoint', 'ppt'),
       ('Microsoft PowerPoint PPTX', 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'pptx'),
       ('AVI Video', 'video/avi', 'avi'),
       ('MOV Video', 'video/quicktime', 'mov'),
       ('WAV Audio', 'audio/wav', 'wav'),
       ('RAR Archive', 'application/x-rar-compressed', 'rar'),
       ('JSON File', 'application/json', 'json'),
       ('CSV File', 'text/csv', 'csv');
